# Numpy

## Install NumPy Library

In [ ]:
# Install NumPy using PIP
pip install numpy

In [ ]:
# Install NumPy using Conda
conda install numpy


## Creating NumPy Arrays

In [ ]:
# Syntax to create NumPy array
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)


| Array | Description |
| --- | --- |
|object|	It represents the collection object. It can be a list, tuple, dictionary, set, etc.|
|dtype|	We can change the data type of the array elements by changing this option to the specified type. The default is none.|
|copy|	It is optional. By default, it is true which means the object is copied.|
|order|	There can be 3 possible values assigned to this option. It can be C (column order), R (row order), or A (any)|
|subok|	The returned array will be base class array by default. We can change this to make the subclasses passes through by setting this option to true.|
|ndmin|	It represents the minimum dimensions of the resultant array.|

In [1]:
# Import Libraries
import numpy as np

### Create NumPy Array using List

In [3]:
# Create ndarray
arr1 = np.array([10,20,30])
arr1

array([10, 20, 30])

### Create a Multi-Dimensional Array

In [4]:
# Create multi dimensional array
arr2 = np.array([[10,20,30],[40,50,60]])
arr2

array([[10, 20, 30],
       [40, 50, 60]])

### Fix The Minimum Dimensions

In [5]:
# Minimum dimension
arr3 = np.array([10, 20, 30,40], ndmin = 2)
arr3

## ndmin param ki madad sy ham minimum dimension set kar sakty hen 

array([[10, 20, 30, 40]])

### Change The Data Type

In [6]:
#dtype parameter 
arr4 = np.array([10, 20, 30], dtype = complex)
arr4

## dtype param ki madad sy pahly hi datatype define kar sakty hen

array([10.+0.j, 20.+0.j, 30.+0.j])

### Get the Dimensions of an Array

In [8]:
# Get dimension of the array
arr5 = np.array([[1, 2, 3, 4], [7, 8, 6, 7], [9, 10, 11, 12]]) 
print(arr5.ndim)
arr5

## ndim param ki madad say ham array ki dimension find kar sakty hen 

2


array([[ 1,  2,  3,  4],
       [ 7,  8,  6,  7],
       [ 9, 10, 11, 12]])

### Get The Size of Each Array Element

In [9]:
# Finding the size of each item in the array  
arr6 = np.array([10,20,30])
print("Each item contain in bytes :",arr6.itemsize)

## itemsize function sy hum array ky har item ka size find kar sakty hen 

Each item contain in bytes : 4


### Get The Data Type of Each Array Item

In [10]:
# Finding the data type of each array item  
arr7 = np.array([10,20,30])  
print("Each item is of the type", arr7.dtype)

Each item is of the type int32


### Get the Shape and Size of Array

In [11]:
# Get shape and size of array
arr8 = np.array([[10,20,30,40],[60,70,80,90]])  
print("Array Size:", arr8.size)  
print("Shape:", arr8.shape)

Array Size: 8
Shape: (2, 4)


### NumPy Array Data Types

| Data Type | Description |
| -- | ----------- |
|bool_|	It represents the boolean value indicating true or false. It is stored as a byte.|
|int_|	It is the default type of integer. It is identical to long type in C that contains 64 bit or 32-bit integer.|
|intc|	It is similar to the C integer (c int) as it represents 32 or 64-bit int.|
|intp|	It represents the integers that are used for indexing.|
|int8|	It is the 8-bit integer identical to a byte. The range of the value is -128 to 127.|
|int16|	It is the 2-byte (16-bit) integer. The range is -32768 to 32767.|
|int32|	It is the 4-byte (32-bit) integer. The range is -2147483648 to 2147483647.|
|int64|	It is the 8-byte (64-bit) integer. The range is -9223372036854775808 to 9223372036854775807.|
|uint8|	It is the 1-byte (8-bit) unsigned integer.|
|uint16|	It is the 2-byte (16-bit) unsigned integer.|
|uint32|	It is the 4-byte (32-bit) unsigned integer.|
|uint64|	It is the 8 bytes (64-bit) unsigned integer.|
|float_|	It is identical to float64.|
|float16|	It is the half-precision float. 5 bits are reserved for the exponent. 10 bits are reserved for the mantissa, and 1 bit is reserved for the sign.|
|float32|	It is a single-precision float. 8 bits are reserved for the exponent, 23 bits are reserved for the mantissa, and 1 bit is reserved for the sign.|
|float64|	It is the double-precision float. 11 bits are reserved for the exponent, 52 bits are reserved for the mantissa, 1 bit is used for the sign.|
|complex_|	It is identical to complex128.|
|complex64|	It is used to represent the complex number where the real and imaginary part shares 32 bits each.|
|complex128|	It is used to represent the complex number where the real and imaginary part shares 64 bit each.|