# Numpy

## Install NumPy Library

In [ ]:
# Install NumPy using PIP
pip install numpy

In [ ]:
# Install NumPy using Conda
conda install numpy


## Creating NumPy Arrays

In [ ]:
# Syntax to create NumPy array
numpy.array(object, dtype = None, copy = True, order = None, subok = False, ndmin = 0)


| Array | Description |
| --- | --- |
|object|	It represents the collection object. It can be a list, tuple, dictionary, set, etc.|
|dtype|	We can change the data type of the array elements by changing this option to the specified type. The default is none.|
|copy|	It is optional. By default, it is true which means the object is copied.|
|order|	There can be 3 possible values assigned to this option. It can be C (column order), R (row order), or A (any)|
|subok|	The returned array will be base class array by default. We can change this to make the subclasses passes through by setting this option to true.|
|ndmin|	It represents the minimum dimensions of the resultant array.|

In [1]:
# Import Libraries
import numpy as np

### Create NumPy Array using List

In [3]:
# Create ndarray
arr1 = np.array([10,20,30])
arr1

array([10, 20, 30])

### Create a Multi-Dimensional Array

In [4]:
# Create multi dimensional array
arr2 = np.array([[10,20,30],[40,50,60]])
arr2

array([[10, 20, 30],
       [40, 50, 60]])

### Create a Sequence of Integers using arange()

In [12]:
#Create a sequence of integers
# from 0 to 20 with steps of 3
arr21= np.arange(0, 20, 3)
print ("A sequential array with steps of 3:\n", arr21)

A sequential array with steps of 3:
 [ 0  3  6  9 12 15 18]


### Single Element Indexing

In [13]:
# Access single element using index 
arr22 = np.arange(11)
print(arr22)
print(arr22[2])
print(arr22[-2])

[ 0  1  2  3  4  5  6  7  8  9 10]
2
9


### Multi-Dimenstional Array Indexing

In [15]:
# Access multi-dimensional array element
# using array indexing
arr23 =np.array([[10,20,30,40,50],[20,30,50,10,30]])
print(arr23)
#[[10 20 30 40 50]
# [20 30 50 10 30]]

print(arr23.shape)

print(arr23[1,1])
print(arr23[0,4])
print(arr23[1,-1])

[[10 20 30 40 50]
 [20 30 50 10 30]]
(2, 5)
30
50
30


### Fix The Minimum Dimensions

In [5]:
# Minimum dimension
arr3 = np.array([10, 20, 30,40], ndmin = 2)
arr3

## ndmin param ki madad sy ham minimum dimension set kar sakty hen 

array([[10, 20, 30, 40]])

### Change The Data Type

In [6]:
#dtype parameter 
arr4 = np.array([10, 20, 30], dtype = complex)
arr4

## dtype param ki madad sy pahly hi datatype define kar sakty hen

array([10.+0.j, 20.+0.j, 30.+0.j])

### Get the Dimensions of an Array

In [8]:
# Get dimension of the array
arr5 = np.array([[1, 2, 3, 4], [7, 8, 6, 7], [9, 10, 11, 12]]) 
print(arr5.ndim)
arr5

## ndim param ki madad say ham array ki dimension find kar sakty hen 

2


array([[ 1,  2,  3,  4],
       [ 7,  8,  6,  7],
       [ 9, 10, 11, 12]])

### Get The Size of Each Array Element

In [9]:
# Finding the size of each item in the array  
arr6 = np.array([10,20,30])
print("Each item contain in bytes :",arr6.itemsize)

## itemsize function sy hum array ky har item ka size find kar sakty hen 

Each item contain in bytes : 4


### Get The Data Type of Each Array Item

In [10]:
# Finding the data type of each array item  
arr7 = np.array([10,20,30])  
print("Each item is of the type", arr7.dtype)

Each item is of the type int32


### Get the Shape and Size of Array

In [11]:
# Get shape and size of array
arr8 = np.array([[10,20,30,40],[60,70,80,90]])  
print("Array Size:", arr8.size)  
print("Shape:", arr8.shape)

Array Size: 8
Shape: (2, 4)


### NumPy Array Data Types

| Data Type | Description |
| -- | ----------- |
|bool_|	It represents the boolean value indicating true or false. It is stored as a byte.|
|int_|	It is the default type of integer. It is identical to long type in C that contains 64 bit or 32-bit integer.|
|intc|	It is similar to the C integer (c int) as it represents 32 or 64-bit int.|
|intp|	It represents the integers that are used for indexing.|
|int8|	It is the 8-bit integer identical to a byte. The range of the value is -128 to 127.|
|int16|	It is the 2-byte (16-bit) integer. The range is -32768 to 32767.|
|int32|	It is the 4-byte (32-bit) integer. The range is -2147483648 to 2147483647.|
|int64|	It is the 8-byte (64-bit) integer. The range is -9223372036854775808 to 9223372036854775807.|
|uint8|	It is the 1-byte (8-bit) unsigned integer.|
|uint16|	It is the 2-byte (16-bit) unsigned integer.|
|uint32|	It is the 4-byte (32-bit) unsigned integer.|
|uint64|	It is the 8 bytes (64-bit) unsigned integer.|
|float_|	It is identical to float64.|
|float16|	It is the half-precision float. 5 bits are reserved for the exponent. 10 bits are reserved for the mantissa, and 1 bit is reserved for the sign.|
|float32|	It is a single-precision float. 8 bits are reserved for the exponent, 23 bits are reserved for the mantissa, and 1 bit is reserved for the sign.|
|float64|	It is the double-precision float. 11 bits are reserved for the exponent, 52 bits are reserved for the mantissa, 1 bit is used for the sign.|
|complex_|	It is identical to complex128.|
|complex64|	It is used to represent the complex number where the real and imaginary part shares 32 bits each.|
|complex128|	It is used to represent the complex number where the real and imaginary part shares 64 bit each.|

## Operations Using in NumPy

### Arithmetic Operations

In [16]:
# Apply arithmetic operations on numpy arrays
arr1 = np.arange(16).reshape(4,4)
arr2 = np.array([1, 3, 2, 4])

# add()
add_arr = np.add(arr1,arr2)
print("Adding two arrays:\n",add_arr)

# substract()
sub_arr=np.subtract(arr1,arr2)
print("Subtracting two arrays:\n",sub_arr)

# multiply()
mul_arr = np.multiply(arr1, arr2)
print("Multiplying the two arrays:\n",mul_arr)

# divide()
div_arr = np.divide(arr1, arr2)
print("Dividing the two arrays:\n",div_arr)


Adding two arrays:
 [[ 1  4  4  7]
 [ 5  8  8 11]
 [ 9 12 12 15]
 [13 16 16 19]]
Subtracting two arrays:
 [[-1 -2  0 -1]
 [ 3  2  4  3]
 [ 7  6  8  7]
 [11 10 12 11]]
Multiplying the two arrays:
 [[ 0  3  4 12]
 [ 4 15 12 28]
 [ 8 27 20 44]
 [12 39 28 60]]
Dividing the two arrays:
 [[ 0.          0.33333333  1.          0.75      ]
 [ 4.          1.66666667  3.          1.75      ]
 [ 8.          3.          5.          2.75      ]
 [12.          4.33333333  7.          3.75      ]]


### numpy.reciprocol()

In [17]:
# To perform Reciprocal operation
arr1 = np.array([50, 10.3, 5, 1, 200])
rep_arr1=np.reciprocal(arr1)
print("After applying reciprocal function:\n",rep_arr1)
#After applying reciprocal function:

# Anotehr Example
arr2 = np.array([20], dtype = int)
rep_arr2=np.reciprocal(arr2)
print("After applying reciprocal function:\n",rep_arr2)
#After applying reciprocal function:

After applying reciprocal function:
 [0.02       0.09708738 0.2        1.         0.005     ]
After applying reciprocal function:
 [0]


### numpy.power()

In [19]:
# To perform power operation
arr1 = np.array([3, 10, 5])
pow_arr1 = np.power(arr1, 3)
print("Applying power function:\n",pow_arr1)


arr2 = np.array([3, 2, 1])
print("My second array:\n",arr2)
pow_arr2=np.power(arr1, arr2)
print("Applying power function again:\n",pow_arr2)



Applying power function:
 [  27 1000  125]
My second array:
 [3 2 1]
Applying power function again:
 [ 27 100   5]


### numpy.mod()

In [21]:
# To perform mod function
# on NumPy array
arr1 = np.array([7, 20, 13])
arr2 = np.array([3, 5, 2])

# mod()
mod_arr = np.mod(arr1, arr2)
print("Applying mod() function:",mod_arr)

## mod function, first array ky har element ko second array ky har element sy divide kar ky remainder return karta hai.
## or remainder function bhi yahi kaam karta hai.
# remainder()
mod_arr = np.remainder(arr1, arr2)
print("Applying remainder() function:",mod_arr)


Applying mod() function: [1 0 1]
Applying remainder() function: [1 0 1]
